name: Publish to npm

on:
  push:
    branches:
      - master

jobs:
  version-check:
    name: Check Version Bump
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package-version.outputs.version }}
      version-changed: ${{ steps.check-version.outputs.changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get current package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Check if version changed
        id: check-version
        run: |
          git diff HEAD^ HEAD -- package.json | grep '"version"' && echo "changed=true" >> $GITHUB_OUTPUT || echo "changed=false" >> $GITHUB_OUTPUT

      - name: Fail if version not bumped
        if: steps.check-version.outputs.changed == 'false'
        run: |
          echo "❌ Error: Version in package.json was not bumped!"
          echo "Please run 'npm version patch|minor|major' before merging to master."
          exit 1

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: version-check
    if: needs.version-check.outputs.version-changed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type check
        run: npm run type-check

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a v${{ needs.version-check.outputs.version }} -m "Release v${{ needs.version-check.outputs.version }}"
          git push origin v${{ needs.version-check.outputs.version }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.version-check.outputs.version }}
          release_name: Release v${{ needs.version-check.outputs.version }}
          body: |
            ## 🚀 Release v${{ needs.version-check.outputs.version }}

            **Package published to npm:** [@emaillistverify/sdk@${{ needs.version-check.outputs.version }}](https://www.npmjs.com/package/@emaillistverify/sdk)

            ### Installation
            ```bash
            npm install emaillistverify-sdk-js@${{ needs.version-check.outputs.version }}
            ```

            See [CHANGELOG.md](./CHANGELOG.md) for detailed release notes.
          draft: false
          prerelease: false
